# Generated by Django 5.1.5 on 2025-01-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('create_dt', models.DateTimeField()),
                ('update_dt', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mapviewer.user'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mapviewer.user'),
        ),
    ]
