# Generated by Django 5.1.5 on 2025-01-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapviewer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="embed_link",
            field=models.URLField(max_length=500),
        ),
    ]
