# Generated by Django 5.1.5 on 2025-01-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapviewer', '0002_user_image_private_waypoint_private_image_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='embed_link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='latitude',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='longitude',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
